### ISSUE TITLE
Q Review Customer Feedback 3

### ISSUE THREAD

**Issue by boycao** [KeegJordan/CSE403#10]
I think team slacker did a good job. I can find the user manual easily on the repo, and it contains detailed instructions. The user interface manual also looks good, well documenting the use cases that help me understand how to use this application. My only concern is that whether you could make the install and implementation process for the Q Review more user-friendly. From my personal experience using Github on Slack, the only step I need for installing Github is to search for Github in the "Apps directory" and install it with one click. I am wondering whether you could simplify the installation process without making users set local servers and local environment.

**Comment by kj-dev-b** [comment]
Thanks for the feedback. local servers are purely for running the app
