### ISSUE TITLE
Q Review customer feedback 4

### ISSUE THREAD

**Issue by boycao** [KeegJordan/CSE403#11]
For this week's peer review, I spent lots of time on the setting up QReview. I have never installed an app from slack.api. For a first-time user, I found it is difficult and really time-consuming to set up the dependency for the project. The user manual did not clearly state what dependencies are needed and how to install, neither state the path for the dependencies. A better documentation and detailed steps will be awesome for me to install the project. I hope you could put more details into the user manual. Even though, there are too many steps to set up the environment. I suggest you try to integrate the dependencies and the main projects.

**Comment by kj-dev-b** [comment]
Hey thanks for the feedback. We just updated both the live environment and the local enviroment configuration. Check it out again when you get the chance and let us know if there are still issues
