### ISSUE TITLE
Deployed app in CI

### ISSUE THREAD

**Issue by izgzhen** [KeegJordan/CSE403#12]
Hi, I saw that your CI is actually shipping some code to heroku. How can I test out this continuously deployed services? How (if any) do you make sure that the code isn't broken after being deployed? What kind of testing are you guys performing?

**Comment by kj-dev-b** [comment]
The deploy won't take place until the tests run by Travis CI all pass. The tests are run using the Mocha framework and a passing test suite is our indication for a working production build ready for deployment.

**Comment by izgzhen** [comment]
I see. Thanks for clarification!
