### ISSUE TITLE
Q Review Customer Feedback 2

### ISSUE THREAD

**Issue by audreytnt** [KeegJordan/CSE403#5]
Q Review Customer Feedback

Great report! I really appreciate the use of examples when explaining your interface; it was easy to see how one would go about using Q Review and what it will be capable of. From the description, it seems very handy and like something I would like to use! The diagram itself was clear and concise; I could get a general idea of how Q Review is going to work. The labeled arrows and differently colored resources were also a nice touch. Although there was some text in the diagram, a more detailed explanation (like a paragraph after the diagram) would have been nice to flesh out the details of what exactly each component does and how they connect. Also you mention what technologies you’ll use to implement the events handler and Slack bot but not the last internal resource (GitHub message creator). I also like how you added a section to specifically address previous feedback. Also, it would probably be better to place the architecture info earlier in the document to better integrate it (we made this mistake too). Overall good job, I just suggest more details but I can still get a good idea of what you are building and how you are going to go about it.

(1pt) The document builds on the original project proposal
(1pt) There is an architecture diagram
(1pt) The architecture diagram is explained in English
(1pt) The system's interface is documented. (For graphical interfaces, a UI mockup should be included. For command-line interfaces, the document should explain how a user interacts with it. For components of larger systems, the document should explain how the component interacts with the system around it.)
(1pt) The document contains discussion of tools and APIs that the team plans to use

**Comment by kj-dev-b** [comment]
Thanks for the feedback! We'll look into your suggestions
