### ISSUE TITLE
Team members should watch this repo

### ISSUE THREAD

**Issue by izgzhen** [KeegJordan/CSE403#6]
@KeegJordan I just noticed that only three people watched this repo, just me, Mike, and Tim. Since github's issue tracker is useful and I might use it more frequently, can you try to get all other team members subscribed?

**Comment by kj-dev-b** [comment]
Aha, just started watching. Will be more on top of responding to issues. Thanks

**Comment by izgzhen** [comment]
@AnnabelleZ Hi, can you try to watch this as well? This helps you keep track of the project activities.

**Comment by izgzhen** [comment]
@KeegJordan You can close this issue after your people are onboard.

**Comment by AnnabelleZ** [comment]
I subscribed to it yesterday, is that what you mean by "watch this repo"?

**Comment by izgzhen** [comment]
<img width="160" alt="screen shot 2019-02-13 at 8 04 18 pm" src="https://user-images.githubusercontent.com/7168454/52761999-8e5efd80-2fca-11e9-874f-86067165166a.png">

Like this? I normally only get emails from a repo if I watched it.

**Comment by izgzhen** [comment]
If you are a collaborator of this GitHub project, you will potentially receive emails (but I am not sure). Just a hint and you may close this issue if you can receive notifications. :)
